### ISSUE TITLE
Notification on save

### ISSUE THREAD

**Issue by Krato** [joedixon/nova-translation#1]
Thanks for this package. Works very well 👍 

Maybe can yo add a toast notification when a translation is saved. Thanks!

**Comment by joedixon** [comment]
Do you mean when adding a new translation or updating an existing?

**Comment by Krato** [comment]
Everything should show a message yes?

**Comment by joedixon** [comment]
When updating a translation, you get the green check mark to notify you changes have been applied successfully.

<img width="380" alt="screenshot 2019-01-14 at 08 01 45" src="https://user-images.githubusercontent.com/3438564/51101526-d1af2c00-17d2-11e9-9d1f-88d54e86e2d5.png">

When creating a new translation, you get the toaster.

<img width="323" alt="screenshot 2019-01-14 at 08 02 34" src="https://user-images.githubusercontent.com/3438564/51101532-d7a50d00-17d2-11e9-9a76-e8b0be8187d0.png">

I will look into adding the toaster when updating a translation in due course.
