### ISSUE TITLE
Exclude Translations

### ISSUE THREAD

**Issue by StanBarrows** [joedixon/nova-translation#2]
Hey great package!

is there a way to exclude translations? For example: Default Nova Translations should not be handled by my application users.

Cheers,
Stan

**Comment by joedixon** [comment]
Hi Stan,

Sorry for the delay getting back to you. Not at the moment, but I don't think it would be too much of a stretch. Would be open to a PR if you're interested. Would probably need to go on the underlying [Laravel Translation](https://github.com/joedixon/laravel-translation) package.

Thanks,
Joe
