### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by refucktor** [joedixon/nova-translation#7]
Hi, thanks for your effort.
I wonder if you find time to update the version requirement of this package to match your latest release for "laravel-translation".
Cause now during the installation, we are having some issues related to conflicts with the minimum-stability as it requires `joedixon/laravel-translation[v0.2.0, v0.2.1]`
Again thanks for your work!

**Comment by joedixon** [comment]
Hi, I just tagged v0.3.0 and updated the dependency.

Does that solve your issue?

**Comment by refucktor** [comment]
Thank you very much! We can close this issue
